version: '2'
services:
    php:
        build: .
        volumes:
            - ../:/var/www/html
        ports:
            - "9000:9000"
        command: php -S 0.0.0.0:9000
        container_name: desing_pattern_php